package com.ec.proxy.model;

import java.util.Date;

public class Proxies {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxies.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxies.host
     *
     * @mbg.generated
     */
    private String host;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxies.port
     *
     * @mbg.generated
     */
    private Integer port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxies.protl
     *
     * @mbg.generated
     */
    private String protl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxies.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxies.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxies.createby
     *
     * @mbg.generated
     */
    private String createby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxies.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxies.errors
     *
     * @mbg.generated
     */
    private Integer errors;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxies.id
     *
     * @return the value of proxies.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxies.id
     *
     * @param id the value for proxies.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxies.host
     *
     * @return the value of proxies.host
     *
     * @mbg.generated
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxies.host
     *
     * @param host the value for proxies.host
     *
     * @mbg.generated
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxies.port
     *
     * @return the value of proxies.port
     *
     * @mbg.generated
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxies.port
     *
     * @param port the value for proxies.port
     *
     * @mbg.generated
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxies.protl
     *
     * @return the value of proxies.protl
     *
     * @mbg.generated
     */
    public String getProtl() {
        return protl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxies.protl
     *
     * @param protl the value for proxies.protl
     *
     * @mbg.generated
     */
    public void setProtl(String protl) {
        this.protl = protl == null ? null : protl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxies.username
     *
     * @return the value of proxies.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxies.username
     *
     * @param username the value for proxies.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxies.password
     *
     * @return the value of proxies.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxies.password
     *
     * @param password the value for proxies.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxies.createby
     *
     * @return the value of proxies.createby
     *
     * @mbg.generated
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxies.createby
     *
     * @param createby the value for proxies.createby
     *
     * @mbg.generated
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxies.createtime
     *
     * @return the value of proxies.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxies.createtime
     *
     * @param createtime the value for proxies.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxies.errors
     *
     * @return the value of proxies.errors
     *
     * @mbg.generated
     */
    public Integer getErrors() {
        return errors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxies.errors
     *
     * @param errors the value for proxies.errors
     *
     * @mbg.generated
     */
    public void setErrors(Integer errors) {
        this.errors = errors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxies
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Proxies other = (Proxies) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getHost() == null ? other.getHost() == null : this.getHost().equals(other.getHost()))
            && (this.getPort() == null ? other.getPort() == null : this.getPort().equals(other.getPort()))
            && (this.getProtl() == null ? other.getProtl() == null : this.getProtl().equals(other.getProtl()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getCreateby() == null ? other.getCreateby() == null : this.getCreateby().equals(other.getCreateby()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getErrors() == null ? other.getErrors() == null : this.getErrors().equals(other.getErrors()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxies
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getHost() == null) ? 0 : getHost().hashCode());
        result = prime * result + ((getPort() == null) ? 0 : getPort().hashCode());
        result = prime * result + ((getProtl() == null) ? 0 : getProtl().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getCreateby() == null) ? 0 : getCreateby().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getErrors() == null) ? 0 : getErrors().hashCode());
        return result;
    }
}